#version 450
layout (local_size_x = 1) in;

#define MAX_DEPTH 32

// Output image
layout(set = 0, binding = 0) buffer buf_img_accu { vec4 img_accu[]; };
layout(set = 0, binding = 1) writeonly buffer buf_img_out { vec4 img_out[]; };

// Nodes BB, index and triangle count
layout(set = 0, binding = 2) readonly buffer buf_nodes_bb { float nodes_bb[]; };
layout(set = 0, binding = 3) readonly buffer buf_nodes_index_tricount { int nodes_index_tricount[]; };
layout(set = 0, binding = 4) readonly buffer buf_tris_opt { float tris_opt[]; };
layout(set = 0, binding = 5) readonly buffer buf_tris_normals { float tris_normals[]; };
layout(set = 0, binding = 6) readonly buffer buf_tris_mats { int tris_mats[]; };

// materials
layout(set = 0, binding = 7) readonly buffer buf_mats { float mats[]; };

// hdri
layout(binding = 8, rgba32f) readonly uniform image2D hdri_image;


layout(constant_id = 0) const float image_width = 0;
layout(constant_id = 1) const float image_height = 0;

// Kompute supports push constants updated on dispatch
layout(push_constant) readonly uniform PushConstants {
    mat4 viewMatrix;
    mat4 inverseProjectionMatrix;
    vec3 camPos;
    uint frameindex;
    float exposure;
} camdata;

#define PI 3.1415926535897932384626433832795
#define FLT_MAX 3.402823466e+38
#define FLT_EPSILON 1.192092896e-07F 

struct Ray
{
	vec3 Origin;
	vec3 Direction;
	vec3 DirectionInverse;
};

struct BoundingBox
{
    vec3 center;
    vec3 extends;
};

struct Node
{
	BoundingBox boundingBox;
	int index;
	int triangleCount;
};

struct HitInfo {
	vec3 position;
	vec3 normal;
	int materialIndex;
};

struct BVHHitInfo {
	float dist;
	float u;
	float v;
	int triIndex;
};

struct TriangleOptimized
{
	vec3 v0;
	vec3 e1;
	vec3 e2;
};

TriangleOptimized GetTriangleOptimized(uint triIndex){
    uint triOffset = 9 * triIndex;

    vec3 v0 = vec3(
    tris_opt[triOffset],
    tris_opt[triOffset+ 1],
    tris_opt[triOffset+ 2]);

    vec3 e1 = vec3(
    tris_opt[triOffset + 3],
    tris_opt[triOffset + 4],
    tris_opt[triOffset + 5]);

    vec3 e2 = vec3(
    tris_opt[triOffset + 6],
    tris_opt[triOffset + 7],
    tris_opt[triOffset + 8]);

    return TriangleOptimized(v0, e1, e2);
}

struct Material {
	vec3 Albedo;
	vec3 Emission;
	float Roughness;
	float Transparency;
	float IOR;
};

Material GetMaterial(uint materialIndex){
    uint matOffset = 9 * materialIndex;

    vec3 albedo = vec3(
    mats[matOffset],
    mats[matOffset+ 1],
    mats[matOffset+ 2]);

    vec3 emission = vec3(
    mats[matOffset + 3],
    mats[matOffset + 4],
    mats[matOffset + 5]);

    float roughness = mats[matOffset + 6];
    float transparency = mats[matOffset + 7];
    float ior = mats[matOffset + 8];

    return Material(albedo, emission, roughness, transparency, ior);
}

BoundingBox GetNodeBB(uint nodeIndex){
    uint bbOffset = 6 * nodeIndex;

    vec3 center = vec3(
    nodes_bb[bbOffset],
    nodes_bb[bbOffset + 1],
    nodes_bb[bbOffset + 2]);

    vec3 extends = vec3(
    nodes_bb[bbOffset + 3],
    nodes_bb[bbOffset + 4],
    nodes_bb[bbOffset + 5]);

    return BoundingBox(center, extends);
}

Node GetNode(int nodeIndex){
    Node node;
    node.boundingBox = GetNodeBB(nodeIndex);
    node.index = nodes_index_tricount[nodeIndex*2];
    node.triangleCount = nodes_index_tricount[nodeIndex*2 + 1];
    return node;
}

const float ACE_a = 2.51f;
const float ACE_b = 0.03f;
const float ACE_c = 2.43f;
const float ACE_d = 0.59f;
const float ACE_e = 0.14f;

vec3 ACESFilm(vec3 x)
{
    vec3 aceColor = clamp((x * (ACE_a * x + ACE_b)) / (x * (ACE_c * x + ACE_d) + ACE_e), 0.0, 1.0);
    return aceColor;
}

vec3 LinearToSRGB(vec3 color) {
    color = clamp(color, 0.0f, 1.0f);
    return mix(
        1.055f * pow(color, vec3(1.0 / 2.4)) - 0.055,
        color * 12.92,
        lessThan(color, vec3(0.0031308))
    );
}

uint NextRandom(inout uint state)
{
    state = state * 747796405 + 2891336453;
    uint result = ((state >> ((state >> 28) + 4)) ^ state) * 277803737;
    result = (result >> 22) ^ result;
    return result;
}

float RandomValue(inout uint state)
{
    return NextRandom(state) / 4294967295.0; // 2^32 - 1
}

// Random value in normal distribution (with mean=0 and sd=1)
float RandomValueNormalDistribution(inout uint state)
{
    // Thanks to https://stackoverflow.com/a/6178290
    float theta = 2 * 3.1415926 * RandomValue(state);
    float rho = sqrt(-2 * log(RandomValue(state)));
    return rho * cos(theta);
}

// Calculate a random direction
vec3 RandomDirection(inout uint state)
{
    // Thanks to https://math.stackexchange.com/a/1585996
    float x = RandomValueNormalDistribution(state);
    float y = RandomValueNormalDistribution(state);
    float z = RandomValueNormalDistribution(state);
    return normalize(vec3(x, y, z));
}

vec3 RandomInUnitSphere(inout uint state)
{
    return normalize(vec3(RandomValue(state) * 2.0 - 1.0, RandomValue(state) * 2.0 - 1.0f, RandomValue(state) * 2.0 - 1.0f));
}


vec4 SampleHDRIFromDirection(in vec3 worldDir)
{
	// Compute spherical coordinates
	float longitude = atan(worldDir.z, worldDir.x);  // Ranges from -pi to pi
	float latitude = asin(worldDir.y);          // Ranges from -pi/2 to pi/2

	// Convert to normalized UV coordinates
	float u = (longitude + PI) / (2.0 * PI); // Map from [-pi, pi] to [0,1]
	float v = (0.5 * PI - latitude) / PI;    // Map from [-pi/2, pi/2] to [0,1], flip v

	// Convert to pixel coordinates
    ivec2 pixelCoords = ivec2(u * 4096, v * 2048);
	return imageLoad(hdri_image, pixelCoords);
}




float RayBBIntersection(in BoundingBox bbox, in Ray ray)
{
	vec3 l1 = (bbox.center - ray.Origin) * ray.DirectionInverse;
	vec3 l2 = bbox.extends * ray.DirectionInverse;

	vec3 tMin = l1 - l2;
	vec3 tMax = l1 + l2;

	vec3 t2 = max(tMin, tMax);
	float tFar = min(min(t2.x, t2.y), t2.z);

	if (tFar < 0.0f)
		return FLT_MAX;

	vec3 t1 = min(tMin, tMax);
	float tNear = max(max(t1.x, t1.y), t1.z);

	if (tNear > tFar)
		return FLT_MAX;

	return tNear;
}

bool RayTriangleIntersection(in TriangleOptimized tri, in Ray ray, out BVHHitInfo hitInfo)
{
	vec3 h = cross(ray.Direction, tri.e2);
	float a = dot(tri.e1, h);

	if (a > -FLT_EPSILON && a < FLT_EPSILON) {
		return false;
	}

	float f = 1.0 / a;
	vec3 s = ray.Origin - tri.v0;
	float u = f * dot(s, h);

	if (u < 0.0 || u > 1.0) {
		return false;
	}

	vec3 q = cross(s, tri.e1);
	float v = f * dot(ray.Direction, q);

	if (v < 0.0 || u + v > 1.0) {
		return false;
	}

	// at this stage we can compute t to find out where the intersection point is on the line
	float t = f * dot(tri.e2, q);

	if (t > FLT_EPSILON) { // ray intersection
		hitInfo.dist = t;
		hitInfo.u = u;
		hitInfo.v = v;
		return true;
	}

	return false;
}


HitInfo IntersectRay(in Ray ray)
{
	BVHHitInfo hitInfo = BVHHitInfo(FLT_MAX - 1.0, 0.0, 0.0, -1);
	int nodeStack[MAX_DEPTH];
	int stackIndex = 0;
	nodeStack[stackIndex++] = 0;

	while (stackIndex > 0) {
		Node currentNode = GetNode(nodeStack[--stackIndex]);

		bool isLeaf = (currentNode.triangleCount > 0);
		if (isLeaf) {
			//Check all triangles in leaf
			BVHHitInfo triHit = BVHHitInfo(FLT_MAX - 1.0, 0.0, 0.0, -1);
			for (int i = currentNode.index; i < currentNode.index + currentNode.triangleCount; i++) {
				bool didHit = RayTriangleIntersection(GetTriangleOptimized(i), ray, triHit);
				if (didHit && triHit.dist < hitInfo.dist) {
					hitInfo.triIndex = i;
					hitInfo.dist = triHit.dist;
					hitInfo.u = triHit.u;
					hitInfo.v = triHit.v;
				}
			}
		}
		else {
			int childIndexA = currentNode.index;
			int childIndexB = currentNode.index + 1;

			float dstA = RayBBIntersection(GetNodeBB(childIndexA), ray);
			float dstB = RayBBIntersection(GetNodeBB(childIndexB), ray);

			// We want to look at closest child node first, so push it last
			bool isNearestA = dstA <= dstB;
			float dstNear = isNearestA ? dstA : dstB;
			float dstFar = isNearestA ? dstB : dstA;
			int childIndexNear = isNearestA ? childIndexA : childIndexB;
			int childIndexFar = isNearestA ? childIndexB : childIndexA;

			if (dstFar < hitInfo.dist) nodeStack[stackIndex++] = childIndexFar;
			if (dstNear < hitInfo.dist) nodeStack[stackIndex++] = childIndexNear;
		}
	}
	

	HitInfo returnHit = HitInfo(vec3(0), vec3(0), -1);


	//If we hit something, work out the position, normal and material
	if (hitInfo.triIndex >= 0) {
		returnHit.position = ray.Origin + ray.Direction * hitInfo.dist;
		
        vec3 n0 = vec3(tris_normals[hitInfo.triIndex * 9], tris_normals[hitInfo.triIndex * 9 + 1], tris_normals[hitInfo.triIndex * 9 + 2]);
        vec3 n1 = vec3(tris_normals[hitInfo.triIndex * 9 + 3], tris_normals[hitInfo.triIndex * 9 + 4], tris_normals[hitInfo.triIndex * 9 + 5]);
        vec3 n2 = vec3(tris_normals[hitInfo.triIndex * 9 + 6], tris_normals[hitInfo.triIndex * 9 + 7], tris_normals[hitInfo.triIndex * 9 + 8]);
        returnHit.normal = (1.0f - hitInfo.u - hitInfo.v) * n0 + hitInfo.u * n1 + hitInfo.v * n2;

        returnHit.materialIndex = tris_mats[hitInfo.triIndex];
	}

	return returnHit;
}


void main() {
    vec3 finalColor = vec3(0.0);
    vec3 contribution = vec3(1.0);

    vec2 uv = vec2((gl_GlobalInvocationID.x % uint(image_width)) / image_width, (gl_GlobalInvocationID.x / image_width) / image_height); 
    vec2 uvCentered = uv * 2.f - 1.f;

    uint randomSeed = camdata.frameindex * uint(image_width * image_height) + gl_GlobalInvocationID.x;

    mat4 inverseViewMatrx = inverse(camdata.viewMatrix);

    vec4 target = camdata.inverseProjectionMatrix * vec4(uvCentered.x, uvCentered.y, 1.f, 1.f);

    Ray ray;
    ray.Origin = camdata.camPos;
    ray.Direction = normalize(vec3(inverseViewMatrx * vec4(normalize(vec3(target) / target.w), 0)));

    for (int i = 0; i < 8; i++){
        ray.DirectionInverse = vec3(1.0 / ray.Direction.x, 1.0 / ray.Direction.y, 1.0 / ray.Direction.z);
        HitInfo hitInfo = IntersectRay(ray);

        // No hit
        if (hitInfo.materialIndex < 0){
            vec3 skyColor = SampleHDRIFromDirection(ray.Direction).rgb;
            finalColor += contribution * skyColor;
            break;
        }

        Material mat = GetMaterial(hitInfo.materialIndex);

        bool doTransmission = false;
        //bool hitInside = glm::dot(ray.Direction, hitdata.Normal) > 0.0f;
        //glm::vec3 normalSurface = hitInside ? -hitdata.Normal : hitdata.Normal;

        // New ray origin offset from last hit position along surface normal
        ray.Origin = hitInfo.position + hitInfo.normal * FLT_EPSILON;


        if (mat.Transparency > 0.0f) {
            // fresnel term    0: no reflect   1: full reflect
            //float fresnel = glm::dot(ray.Direction, -normalSurface);
            float fresnel = dot(ray.Direction, -hitInfo.normal);

            //if (Walnut::Random::Float() < fresnel) {
            //if (Random::Float() < fresnel) {
            doTransmission = true;
            //}
        }


        // Transmission or reflection ray?
        if (doTransmission) {
            //// glsl way (me no workeee, why?)
            //ray.Direction = glm::refract(ray.Direction, hitdata.Normal, hitInside ? mat.IOR : 1.0f / mat.IOR);
            //continue;

            Ray refractionRay;
            //if (RefractionRay(ray.Direction, hitInfo.normal, hitInfo.position, mat.IOR, refractionRay)) {
            //    ray = refractionRay;
        //     continue;
            //}
        }
        else {
            vec3 diffuseRayDir = normalize(hitInfo.normal + RandomInUnitSphere(randomSeed));
           // vec3 diffuseRayDir = normalize(hitInfo.normal + RandomDirection(randomSeed));
            vec3 reflectedVector = reflect(ray.Direction, hitInfo.normal);
            reflectedVector = normalize(mix(reflectedVector, diffuseRayDir, mat.Roughness * mat.Roughness));

            //glm::vec3 randomHemisphereVector = glm::normalize(Util::RandomHemisphere(hitdata.Normal, mat.Roughness));
            //glm::vec3 reflectedVector = glm::reflect(ray.Direction, randomHemisphereVector);

            ray.Direction = reflectedVector;
        }


        finalColor += mat.Emission * contribution;
        contribution *= mat.Albedo;


        // Russian Roulette
        // As the throughput gets smaller, the ray is more likely to get terminated early.
        // Survivors have their value boosted to make up for fewer samples being in the average.
        
        float p = max(contribution.r, max(contribution.g, contribution.b));
        if (RandomValue(randomSeed) > p)
            break;

        // Add the energy we 'lose' by randomly terminating paths
        contribution *= 1.0f / p;
    }
    
    







    // Accumulate as running average
    //vec4 colorIncrease = (vec4(finalColor, 1.0) - img_out[gl_GlobalInvocationID.x]) / camdata.frameindex; 
    //img_out[gl_GlobalInvocationID.x] += colorIncrease;

    vec4 oldColor = img_accu[gl_GlobalInvocationID.x];
    vec4 newColor = oldColor + ((vec4(finalColor, 1.0) - oldColor) / camdata.frameindex); 
    img_accu[gl_GlobalInvocationID.x] = newColor;

    // Color corrected image
    vec3 colorCorrected = LinearToSRGB(ACESFilm(camdata.exposure * newColor.rgb));
    img_out[gl_GlobalInvocationID.x] = vec4(colorCorrected, 1.0);
}